### ISSUE TITLE
Weird error w/ wave

### ISSUE THREAD

**Issue by TheLemon27** [KristalTeam/Kristal#106]
I was testing a wave i made, and the game spit this error back at me:
`Error at src/utils/utils.lua:1535 - attempt to perform arithmetic on local 'y1' (a nil value)`
I can give extra details if prompted, but I'll be honest, I've been looking for an excuse to go to bed and this seems like a good one so I'll respond in the morning, Thanks!

**Comment by JustinSolstice** [comment]
Can you show the script/code? Likely you forgot to set y1 value when referencing it

**Comment by NyakoFox** [comment]
Closing due to lack of response.
