### ISSUE TITLE
attempt to index local 'name'

### ISSUE THREAD

**Issue by KALLBOX778** [KristalTeam/Kristal#11]
Hi, every single time I save a map in the the most recent version of Tiled, this error appears when trying to enter the room.
![image](https://user-images.githubusercontent.com/103757526/179121001-33cb03ec-4fdb-4558-89bb-2769786cbca7.png)

This doesn't happen on the maps in example-stage, but it does after I open them and save.
I have tried different versions of Kristal, but all give the same error.

I don't know how to fix it, and I can't figure out what the issue is in the first place.
It would be great to know what I am doing wrong.
Thanks.

**Comment by KALLBOX778** [comment]
Oh, nevermind I firgured out the issue.
To anyone who has this same issue here's how to fix it.
You have to download an older version of Tiled as of now.
The option that works for me is 1.8.4.
You can download these older versions from the Tiled Github page.

**Comment by NyakoFox** [comment]
oh hey sorry! this was fixed in a development build a while ago but we haven't made a hotfix release yet... we'll be doing that soon!!

**Comment by KALLBOX778** [comment]
oh, thanks for for the info and getting back to me on that
thats good to hear about the hotfix!
