### ISSUE TITLE
ERROR is occurding when trying to write something in create new mod "mod name" and "mod ID"

### ISSUE THREAD

**Issue by Telejaba** [KristalTeam/Kristal#12]
![image](https://user-images.githubusercontent.com/100534810/185451917-369707c3-5487-4165-9313-e80f439f3d19.png)

**Comment by NyakoFox** [comment]
What did you enter? I can't seem to reproduce it.

**Comment by Telejaba** [comment]
Oh lmao I forgot that I opened that issue
Its fixed for me a long time ago
