### ISSUE TITLE
Battles in the light world use the incorrect health values

### ISSUE THREAD

**Issue by Agent517** [KristalTeam/Kristal#16]
Light world battles use the dark world health, despite every other stat (including max health) using the light world version.
This causes the health bar to go far off the side of the screen, as seen in the screenshot.

![image](https://user-images.githubusercontent.com/87152256/188291333-0d53def6-eac4-4d6a-a4b0-247134fdc3e2.png)

**Comment by DiamondBor** [comment]
still an issue, kinda shocked how this isn't fixed yet

**Comment by NyakoFox** [comment]
battles in the light world aren't a priority

**Comment by NyakoFox** [comment]
This has been fixed in 92e4643b3c19f8d0735884118e682eed40f159a5
