### ISSUE TITLE
what was that?

### ISSUE THREAD

**Issue by Aloekunyep** [KristalTeam/Kristal#18]
![Screenshot 2022-11-27 04-46-24](https://user-images.githubusercontent.com/103645165/204115594-818b05a4-8738-4e9c-865c-051db4df15f7.png)

**Comment by Dobby233Liu** [comment]
Are you trying to give yourself items in the main menu?

**Comment by Aloekunyep** [comment]
no

**Comment by Aloekunyep** [comment]
it appeared after this error
![Screenshot 2022-11-27 04-59-19](https://user-images.githubusercontent.com/103645165/204115823-d3f34562-7a9a-4e4a-a9a6-ed4c398366ee.png)

**Comment by NyakoFox** [comment]
Can you send the file?

**Comment by NyakoFox** [comment]
Closing due to lack of response.
