### ISSUE TITLE
The game freeze when trying to open mods folder

### ISSUE THREAD

**Issue by Ferpakenameyea** [KristalTeam/Kristal#265]
I'm currently playing on Windows11 and when I use `open mods folder`, the game window just freezes and nothing showed up. I sure succeeded some time but mostly it just freezes.
And I went to check the mods folder, it exists.

**Comment by Ferpakenameyea** [comment]
I've made a solution, using the `os.execute` to fix this.
https://github.com/KristalTeam/Kristal/pull/266

**Comment by TFLTV** [comment]
Are you sure its not that the mods folder is opening up behind a window or something? The game freezes because its not focused

**Comment by Ferpakenameyea** [comment]
I'm sure it's not, I checked everywhere including the task manager, but nothing showed up and the game is still frozen.
