### ISSUE TITLE
Can't change angle of a bullet?

### ISSUE THREAD

**Issue by TFLTV** [KristalTeam/Kristal#35]
Nothing about setting the angle of an object is ever documented.  bullet.angle doesn't seem to take affect.
`bullet.angle = math.rad(angle)`

**Comment by SylviBlossom** [comment]
it's only documented as part of the Object class, but the variable to change is `bullet.physics.direction` along with `bullet.physics.speed`, or if you want visual rotation to conveniently match bullet direction, you can set `bullet.physics.match_rotation = true` and change `bullet.rotation`.

**Comment by TFLTV** [comment]
tysm!
