### ISSUE TITLE
Weapon attack differences in equip menu

### ISSUE THREAD

**Issue by SuperOfSrb2** [KristalTeam/Kristal#49]
![image](https://github.com/KristalTeam/Kristal/assets/85749337/191efce9-dffa-4060-9c02-1328ce091182)
This screenshot from the latest version of Deltarune displays value indicators for how much more/less attack the item you are hovering over has compared to your current weapon. Differences aren't displayed for defense or magic, even on armors, and armors that increase attack don't have differences.
![image](https://github.com/KristalTeam/Kristal/assets/85749337/518a9b70-c528-43c7-977e-9570d08e4ecd)
Kristal does not have this. Could be nice to add differences for armors, defense and magic, but I don't know how faithful to source Kristal is meant to be.

**Comment by NyakoFox** [comment]
Added with [378231d](https://github.com/KristalTeam/Kristal/commit/378231d9f4b9118881cb747afbf2d6ae0f8eeb7d)
