### ISSUE TITLE
recommend version 1.8.4 of tiled in the wiki?

### ISSUE THREAD

**Issue by maska228** [KristalTeam/Kristal#9]
the wiki just says that this engine uses tiled for its overworld map shit(see [Overworld](https://github.com/KristalTeam/Kristal/wiki/Overworld)), but export of a map in version 1.9.0 doesn't work. in 1.8.4 however(the version maps in [example](https://github.com/KristalTeam/Kristal/tree/main/mods/example)/[template](https://github.com/KristalTeam/Kristal/tree/main/mod_template) are exported in), the export does work.

as the title says, i suggest recommending version 1.8.4 of tiled to be installed, instead of just saying that this engine uses tiled.

**Comment by NyakoFox** [comment]
i'd rather the engine work with 1.9.0 instead of limiting it to an older version of tiled

**Comment by maska228** [comment]
> i'd rather the engine work with 1.9.0 instead of limiting it to an older version of tiled

yeah, i kinda thought you would.

**Comment by NyakoFox** [comment]
[`4a4820f`](https://github.com/KristalTeam/Kristal/commit/4a4820f47265d99db0ef4266ec5d048e2e345479) fixes the crash, but doesn't add the new 1.9.0 features
